name: Ubuntu_Test

on:
  push:
    branches: [ main ]

jobs:
  ubuntu_test:
    runs-on: ubuntu-latest
    steps:
      - name: Install required packages
        run: >
          apt update &&
          apt install -y
          curl
          git
          sudo
      - name: Install dotfiles
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/miyuush/dotfiles/master/setup.sh)"
