name: Ubuntu_Test

on:
  push:
    branches: [ main ]

env:
  BASE_TAG: base:1.0.0

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: .devcontainer/Dockerfile
          ignore: "DL3008","DL4006"

  dockle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      # See: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#local-cache
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Only docker build
        uses: docker/build-push-action@v3
        with:
          context: ./.devcontainer
          load: true
          tags: ${{ env.BASE_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - uses: hands-lab/dockle-action@v1
        with:
          image: ${{ env.BASE_TAG }}
          exit-code: '1'
          exit-level: WARN

  ubuntu_test:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: >
          apt update &&
          apt install -y
          curl
          git
          sudo
      - name: Install dotfiles
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/miyuush/dotfiles/master/setup.sh)"
