name: Ubuntu_Test

on:
  push:
    branches: [ main ]

env:
  BASE_TAG: base:1.0.0

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: .devcontainer/Dockerfile

  ubuntu_test:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: >
          apt update &&
          apt install -y
          curl
          git
          sudo
      - name: Install dotfiles
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/miyuush/dotfiles/master/setup.sh)"
